#=============================================================#
#                        APPLICATION                          #
#=============================================================#
spring.application.name=social.subscriber
#=============================================================#
#                            WEB                              #
#=============================================================#
server.port=8080
#=============================================================#
#                          DATABASE                           #
#=============================================================#
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/user_subscriptions_db
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
r2dbc.migrate.resources-paths=classpath:/db/migration/